### ISSUE TITLE
Live chat qol

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#242]
### What you are suggesting

Use the user's last used name ingame when they speak in live chats, it already uses their hours but currently only their discord nickname and not their last used ingame name

**Comment by phinner** [comment]
Meh, implementing it would require the rewrite of the account session system.
Don't really want to do that for now...

**Comment by JasonP01** [comment]
Could you not just replace the part where it fetches the discord nick with the last used ingame, the last used is fairly easy to get as player info gets it

**Comment by phinner** [comment]
Think about it, you want to have user info, and the only way to do it is `discord ID -> account -> user`, but there is a catch.
With the current system, only "logged-in online users" know to which account they are bound to thanks to their session info, which is a hash of uuid + usid.
So in order to get users that are bound to an account whatever its status, I'll have to add the user ID to the session info.
And this change involves cleaning up the mess of `AccountManager` which I frankly don't want to touch anymore than I need to for now.
